# Generated by Django 5.1.4 on 2025-09-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Grow a Business', 'Grow a Business'), ('New Market Entry', 'New Market Entry')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('questions_answered', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
