# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='charts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]


