# Generated by Django 5.1.4 on 2025-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0002_add_charts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=128, null=True)),
                ('youtube', models.CharField(blank=True, max_length=128, null=True)),
                ('flipkart', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
