# Generated by Django 5.1.4 on 2025-09-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0003_apikeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
