# Generated by Django 5.1.4 on 2025-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0004_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analysis_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
