# Generated by Django 5.1.4 on 2025-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0006_fill_analysis_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_first_iteration',
            field=models.BooleanField(default=True),
        ),
    ]
