# Generated by Django 5.1.4 on 2025-09-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0007_project_is_first_iteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
