# Generated by Django 5.1.4 on 2025-09-21 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0008_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='artisan.project'),
        ),
    ]
